services:
  topaz-dev-postgres:
    image: ankane/pgvector
    container_name: topaz_dev_postgres
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "5444:5444"
    command: >
      postgres -c port=5444 -c timezone=America/Los_Angeles -c max_connections=500 -c shared_buffers=256MB -c work_mem=64MB -c maintenance_work_mem=128MB -c log_statement=all -c log_destination=stderr -c log_directory=/var/log/postgresql -c log_filename=postgresql.log
    volumes:
      - pgTelemetryData:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=telemetry
      - POSTGRES_USER=db_user  
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_PORT=5444
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'db_user', '-d', 'telemetry', '-t', '1' ]
      interval: 2s
      timeout: 100s
      retries: 10

volumes:
  pgTelemetryData:
